Repository modern-python/that-depends, pull requests merged in 2025-02, with the labels that each got.

#156 Fixed documentation and adjusted API for 2.0 release.
  Justfile
  docs/css/code.css
  docs/dev/contributing.md
  docs/index.md
  docs/integrations/fastapi.md
  docs/introduction/inject-factories.md
  docs/introduction/injection.md
  docs/introduction/ioc-container.md
  docs/introduction/scopes.md
  docs/introduction/string-injection.md
  docs/migration/v2.md
  docs/overrides/main.html
  docs/providers/context-resources.md
  docs/providers/factories.md
  mkdocs.yml
  pyproject.toml
  tests/providers/test_context_resources.py
  tests/test_multiple_containers.py
  that_depends/meta.py
  that_depends/providers/context_resources.py
Labels: documentation, enhancement

#157 Fixed link to migration guide in announcement
  docs/overrides/main.html
Labels: documentation

#160 README adjustment and minor documentation fixes.
  LICENSE
  README.md
  docs/integrations/fastapi.md
  docs/introduction/injection.md
  docs/migration/v2.md
  docs/overrides/main.html
  docs/providers/context-resources.md
Labels: documentation

#161 Sync tear down
  docs/providers/resources.md
  docs/providers/singleton.md
  tests/providers/test_resources.py
  tests/test_container.py
  that_depends/container.py
  that_depends/providers/base.py
  that_depends/providers/context_resources.py
  that_depends/providers/resources.py
  that_depends/providers/singleton.py
Labels: documentation, enhancement

#162 Bugfix: container context wrapper
  tests/providers/test_context_resources.py
  that_depends/providers/context_resources.py
Labels: bug

#163 Refactor BaseContainer and BaseContainerMeta
  tests/providers/test_context_resources.py
  tests/test_injection.py
  tests/test_meta.py
  that_depends/__init__.py
  that_depends/container.py
  that_depends/injection.py
  that_depends/meta.py
  that_depends/providers/context_resources.py
Labels: bug

#164 Allow Selectors to use other Providers and strings as selectors
  docs/providers/selector.md
  tests/providers/test_selector.py
  that_depends/providers/selector.py
Labels: enhancement
